/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serialport_SerialPort */

#ifndef _Included_com_serialport_SerialPort
#define _Included_com_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeOpen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeSendBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeSendBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeReceiveBytes
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeReceiveBytes
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeSetBaudRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeSetBaudRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeGetBaudRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeGetBaudRate
  (JNIEnv *, jobject);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeClose
  (JNIEnv *, jobject);

/*
 * Class:     com_serialport_SerialPort
 * Method:    nativeFlush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serialport_SerialPort_nativeFlush
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
